# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"
silent: true
vars:
  ORG: gpmtools
includes:
  build: { taskfile: ./taskfiles/Build.yml }
  generate: { taskfile: ./taskfiles/Generate.yml }
  install: { taskfile: ./taskfiles/Install.yml }
  lint: { taskfile: ./taskfiles/Lint.yml }
  test: { taskfile: ./taskfiles/Test.yml }

tasks:
  default:
    ignore_error: true
    cmds:
      - task --list-all

  stat:
    desc: Display information about the project
    ignore_error: true
    vars:
      PROJECT_LANGUAGE:
        sh: task _repo_languages
      PROJECT_VERSION:
        sh: task _repo_latest_release
      PROJECT_NAME:
        sh: task _project_name
      PROJECT_DESCRIPTION:
        sh: task _repo_description
      REPO_CREATED_AT:
        sh: task _repo_created_at
      PROJECT_ISSUES:
        sh: task _repo_issues
    cmds:
      - gum format "# {{.PROJECT_NAME}}" "{{.PROJECT_DESCRIPTION}}"
      - gum format "* Created at - {{.REPO_CREATED_AT}}" "* Languages - {{.PROJECT_LANGUAGE}}"
      - gum format "### Pending tasks" "{{.PROJECT_ISSUES}}"

  _project_name:
    ignore_error: true
    vars:
      OWNER:
        sh: git remote -v | grep -m 1 origin | awk -F'[:/]' '{print $5}'
      REPO:
        sh: basename $(git rev-parse --show-toplevel)
    cmds:
      - echo {{.OWNER}}/{{.REPO}}

  _repo_created_at:
    ignore_error: true
    cmds:
      - gh repo view --json pushedAt --jq .pushedAt

  _repo_description:
    ignore_error: true
    cmds:
      - gh repo view --json description --jq .description

  _repo_issues:
    ignore_error: true
    cmds:
      - gh recent-issues

  _repo_labels:
    ignore_error: true
    cmds:
      - gh repo view --json labels --jq .labels

  _repo_languages:
    ignore_error: true
    cmds:
      - gh repo view --json languages --jq .languages

  _repo_latest_release:
    ignore_error: true
    cmds:
      - gh repo view --json latestRelease --jq .latestRelease

  _repo_pushed_at:
    ignore_error: true
    cmds:
      - gh repo view --json pushedAt --jq .pushedAt

  _repo_stargazer_count:
    ignore_error: true
    cmds:
      - gh repo view --json stargazerCount --jq .stargazerCount
